/**
 * LaTeX Generator Service
 * Produces publication-ready LaTeX output for literature reviews,
 * synthesis reports, and problem statements.
 */

import type { PaperMetadata } from "./academic-search";
export type { PaperMetadata } from "./academic-search";

// ============================================================================
// Types
// ============================================================================
export interface SynthesisData {
  methodologicalPatterns: string;
  overarchingFindings: string;
  recurringGaps: string;
  impactAssessment: string;
  futureDirections: string;
  identifiedGaps: string[];
}

export interface ProblemStatementData {
  whatIsKnown: string;
  whatIsMissing: string;
  affectedStakeholders: string;
  consequencesOfInaction: string;
  howStudyAddressesGap: string;
  selectedGapIndex: number;
  fullStatement: string;
}

export interface BibFormat {
  format: "APA" | "MLA" | "Chicago" | "IEEE" | "BibTeX";
}

// ============================================================================
// Citation Formatters
// ============================================================================
function formatCitationAPA(paper: PaperMetadata): string {
  const authors = paper.authors.join(", ");
  const journal = paper.journal ? `\textit{${paper.journal}}` : "";
  const volIssue = paper.volume ? `, ${paper.volume}` : "";
  const pages = paper.pages ? `, ${paper.pages}` : "";
  return `${authors} (${paper.year}). ${paper.title}. ${journal}${volIssue}${pages}. https://doi.org/${paper.doi || "N/A"}`;
}

function formatCitationMLA(paper: PaperMetadata): string {
  const authors = paper.authors.join(", ");
  const journal = paper.journal ? `\textit{${paper.journal}}` : "";
  const vol = paper.volume || "";
  const pages = paper.pages || "";
  return `${authors}. \"${paper.title}.\" ${journal}, vol. ${vol}, ${paper.year}, pp. ${pages}.`;
}

function formatCitationIEEE(paper: PaperMetadata): string {
  const authors = paper.authors.join(", ");
  return `[${authors}, \"${paper.title},\" ${paper.journal || ""}, vol. ${paper.volume || ""}, pp. ${paper.pages || ""}, ${paper.year}.]`;
}

function formatCitation(paper: PaperMetadata, format: BibFormat["format"]): string {
  switch (format) {
    case "MLA":
      return formatCitationMLA(paper);
    case "IEEE":
      return formatCitationIEEE(paper);
    case "BibTeX":
      return generateBibTeXEntry(paper);
    case "APA":
    default:
      return formatCitationAPA(paper);
  }
}

function generateBibTeXEntry(paper: PaperMetadata): string {
  const key = paper.authors[0]?.split(" ").pop()?.toLowerCase() || "unknown";
  const authors = paper.authors.join(" and ");
  return `@article{${key}${paper.year},
  title={${paper.title}},
  author={${authors}},
  journal={${paper.journal || ""}},
  volume={${paper.volume || ""}},
  pages={${paper.pages || ""}},
  year={${paper.year}},
  doi={${paper.doi || ""}}
}`;
}

// ============================================================================
// LaTeX Document Assembly
// ============================================================================
function latexPreamble(title: string): string {
  return `\\documentclass[11pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
\\usepackage[margin=1in]{geometry}
\\usepackage{enumitem}
\\usepackage{xcolor}
\\usepackage{hyperref}
\\usepackage{booktabs}
\\usepackage{longtable}
\\usepackage{array}
\\usepackage[most]{tcolorbox}

% Define custom colors
\\definecolor{promptblue}{RGB}{41, 98, 150}
\\definecolor{promptbg}{RGB}{240, 247, 255}
\\definecolor{promptborder}{RGB}{100, 160, 220}
\\definecolor{accentgreen}{RGB}{0, 128, 100}
\\definecolor{warningorange}{RGB}{200, 120, 0}

\\newtcolorbox{resultbox}[1][]{
    colback=promptbg,
    colframe=promptborder,
    coltitle=white,
    fonttitle=\\bfseries\\small,
    title={#1},
    colbacktitle=promptblue,
    boxrule=1pt,
    arc=2mm,
    left=8pt, right=8pt, top=6pt, bottom=6pt,
    enhanced, breakable
}

\\newtcolorbox{gapbox}[1][]{
    colback=orange!5,
    colframe=warningorange,
    coltitle=white,
    fonttitle=\\bfseries\\small,
    title={#1},
    colbacktitle=warningorange,
    boxrule=1pt,
    arc=2mm,
    left=8pt, right=8pt, top=6pt, bottom=6pt,
    enhanced, breakable
}

\\hypersetup{
    colorlinks=true,
    linkcolor=promptblue,
    urlcolor=promptblue,
    citecolor=promptblue
}

\\title{\\textbf{${title}}}
\\author{Generated by Research Accelerant Agent}
\\date{\\today}

\\begin{document}
\\maketitle`;
}

// ============================================================================
// Literature Review Document (MVP)
// ============================================================================
export function generateLiteratureReviewLaTeX(
  papers: PaperMetadata[],
  topic: string,
  yearFrom: number,
  yearTo: number,
  bibFormat: BibFormat["format"] = "APA"
): string {
  const parts: string[] = [];

  parts.push(latexPreamble(`Literature Review: ${topic}`));

  // Search parameters summary
  parts.push(`
\\begin{resultbox}[Search Parameters]
\\begin{itemize}[leftmargin=*]
    \\item \\textbf{Topic:} ${topic}
    \\item \\textbf{Year Range:} ${yearFrom}--${yearTo}
    \\item \\textbf{Studies Retrieved:} ${papers.length}
    \\item \\textbf{Citation Format:} ${bibFormat}
\\end{itemize}
\\end{resultbox}

\\vspace{1em}`);

  // Individual studies
  parts.push(`\\textbf{\\large Reviewed Studies}\\par\\vspace{0.5em}`);

  papers.forEach((paper, index) => {
    const citation = formatCitation(paper, bibFormat);

    parts.push(`
\\textbf{${index + 1}. ${paper.title}}

\\textbf{Full Citation:} ${citation}

\\begin{resultbox}[Study Details]
\\begin{itemize}[leftmargin=*]
    \\item \\textbf{Authors:} ${paper.authors.join(", ")}
    \\item \\textbf{Year:} ${paper.year}
    \\item \\textbf{Journal:} ${paper.journal || "N/A"}
    ${paper.volume ? `    \\item \\textbf{Volume:} ${paper.volume}` : ""}
    ${paper.issue ? `    \\item \\textbf{Issue:} ${paper.issue}` : ""}
    ${paper.pages ? `    \\item \\textbf{Pages:} ${paper.pages}` : ""}
    \\item \\textbf{DOI:} \\href{https://doi.org/${paper.doi || ""}}{${paper.doi || "N/A"}}
    \\item \\textbf{Citation Count:} ${paper.citationCount} (${paper.citationCountSource})
    \\item \\textbf{Access:} \\href{${paper.url}}{${paper.source === "openalex" ? "OpenAlex" : "Semantic Scholar"}}
\\end{itemize}
\\end{resultbox}

\\textbf{Abstract:} ${paper.abstract || "Abstract not available."}\\par\\vspace{0.5em}
`);
  });

  // Summary statistics table
  if (papers.length > 0) {
    const avgCitations = Math.round(papers.reduce((s, p) => s + p.citationCount, 0) / papers.length);
    const yearRange = papers.map((p) => p.year);
    const minYear = Math.min(...yearRange);
    const maxYear = Math.max(...yearRange);

    parts.push(`
\\vspace{1em}
\\textbf{\\large Summary Statistics}\\par\\vspace{0.5em}

\\begin{center}
\\begin{tabular}{lc}
\\toprule
\\textbf{Metric} & \\textbf{Value} \\\\
\\midrule
Total Studies Reviewed & ${papers.length} \\\\
Average Citations per Study & ${avgCitations} \\\\
Publication Year Range & ${minYear}--${maxYear} \\\\
Studies with Open Access PDF & ${papers.filter((p) => p.pdfUrl).length} \\\\
\\bottomrule
\\end{tabular}
\\end{center}`);
  }

  parts.push(`
\\vfill
\\begin{center}
\\textit{Document generated by Research Accelerant Agent on \\today.}
\\end{center}

\\end{document}`);

  return parts.join("\n\n");
}

// ============================================================================
// Synthesis Document (V2)
// ============================================================================
export function generateSynthesisLaTeX(
  papers: PaperMetadata[],
  synthesis: SynthesisData,
  topic: string,
  _bibFormat: BibFormat["format"] = "APA"
): string {
  const parts: string[] = [];

  parts.push(latexPreamble(`Cross-Study Synthesis: ${topic}`));

  // Papers summary table
  parts.push(`
\\textbf{\\large Studies Included in Synthesis}\\par\\vspace{0.5em}

\\begin{longtable}{p{5cm}cc}
\\toprule
\\textbf{Study} & \\textbf{Year} & \\textbf{Citations} \\\\
\\midrule
\\endhead
${papers
  .map((p) => `${p.title.substring(0, 50)}${p.title.length > 50 ? "..." : ""} & ${p.year} & ${p.citationCount} \\\\`)
  .join("\n")}
\\bottomrule
\\end{longtable}

\\vspace{1em}`);

  // Methodological Patterns
  parts.push(`
\\textbf{\\large 1. Methodological Patterns}\\par\\vspace{0.5em}

${synthesis.methodologicalPatterns || "No methodological patterns identified."}

\\vspace{1em}`);

  // Overarching Findings
  parts.push(`
\\textbf{\\large 2. Overarching Findings and Trends}\\par\\vspace{0.5em}

${synthesis.overarchingFindings || "No overarching findings identified."}

\\vspace{1em}`);

  // Recurring Gaps
  parts.push(`
\\textbf{\\large 3. Recurring Gaps and Limitations}\\par\\vspace{0.5em}

${synthesis.recurringGaps || "No recurring gaps identified."}

\\vspace{0.5em}`);

  // Identified Gaps boxes
  if (synthesis.identifiedGaps && synthesis.identifiedGaps.length > 0) {
    synthesis.identifiedGaps.forEach((gap, i) => {
      parts.push(`
\\begin{gapbox}[Gap ${i + 1}]
${gap}
\\end{gapbox}

\\vspace{0.3em}`);
    });
  }

  // Impact Assessment
  parts.push(`
\\vspace{1em}
\\textbf{\\large 4. Impact Assessment}\\par\\vspace{0.5em}

${synthesis.impactAssessment || "No impact assessment available."}

\\vspace{1em}`);

  // Future Directions
  parts.push(`
\\textbf{\\large 5. Future Research Directions}\\par\\vspace{0.5em}

${synthesis.futureDirections || "No future directions identified."}

\\vspace{1em}`);

  parts.push(`
\\vfill
\\begin{center}
\\textit{Synthesis generated by Research Accelerant Agent on \\today.}
\\end{center}

\\end{document}`);

  return parts.join("\n\n");
}

// ============================================================================
// Problem Statement Document (V3)
// ============================================================================
export function generateProblemStatementLaTeX(
  ps: ProblemStatementData,
  topic: string,
  selectedGap?: string
): string {
  const parts: string[] = [];

  parts.push(latexPreamble(`Problem Statement: ${topic}`));

  parts.push(`
\\begin{resultbox}[Definition]
In the context of a research proposal, a problem statement is a concise, clear, and evidence-based description of a specific \\textbf{researchable} issue, a \\textbf{demonstrable} gap in knowledge, or a \\textbf{measurable} real-world challenge that your research is \\textbf{designed to solve}.
\\end{resultbox}

\\vspace{1em}

\\textbf{\\large Structured Problem Statement}\\par\\vspace{0.5em}

\\textbf{1. What is Known}\\\\
${ps.whatIsKnown || "[To be completed]"}

\\vspace{0.5em}

\\textbf{2. What is Missing}\\\\
${ps.whatIsMissing || selectedGap || "[To be completed]"}

\\vspace{0.5em}

\\textbf{3. Affected Stakeholders}\\\\
${ps.affectedStakeholders || "[To be completed]"}

\\vspace{0.5em}

\\textbf{4. Consequences of Inaction}\\\\
${ps.consequencesOfInaction || "[To be completed]"}

\\vspace{0.5em}

\\textbf{5. How the Study Addresses the Gap}\\\\
${ps.howStudyAddressesGap || "[To be completed]"}

\\vspace{1em}

\\begin{resultbox}[Full Problem Statement]
${ps.fullStatement || "[Draft your full problem statement here by synthesizing the above components.]"}
\\end{resultbox}

\\vspace{1em}

\\textbf{\\large Validation Checklist}\\par\\vspace{0.3em}

\\begin{itemize}[leftmargin=*, label=$\\square$]
    \\item Is the problem \\textbf{researchable}? (Can it be investigated through empirical methods?)
    \\item Is the gap \\textbf{demonstrable}? (Can you cite evidence that it exists?)
    \\item Is the challenge \\textbf{measurable}? (Can outcomes be quantified or assessed?)
    \\item Are \\textbf{stakeholders} clearly identified?
    \\item Are \\textbf{consequences of inaction} articulated?
    \\item Does the statement tell reviewers \\textbf{why}, \\textbf{what}, and \\textbf{how}?
\\end{itemize}

\\vfill
\\begin{center}
\\textit{Problem statement generated by Research Accelerant Agent on \\today.}
\\end{center}

\\end{document}`);

  return parts.join("\n\n");
}

// ============================================================================
// Full Pipeline Document (All V1+V2+V3 combined)
// ============================================================================
export function generateFullPipelineLaTeX(
  papers: PaperMetadata[],
  synthesis: SynthesisData,
  ps: ProblemStatementData,
  topic: string,
  yearFrom: number,
  yearTo: number,
  bibFormat: BibFormat["format"] = "APA"
): string {
  const parts: string[] = [];

  parts.push(latexPreamble(`Research Proposal Foundation: ${topic}`));

  // Include literature review
  parts.push(`\\part*{Part I: Literature Review}\\addcontentsline{toc}{part}{Part I: Literature Review}`);
  parts.push(generateLiteratureReviewLaTeX(papers, topic, yearFrom, yearTo, bibFormat));

  // Include synthesis
  parts.push(`\\newpage`);
  parts.push(`\\part*{Part II: Cross-Study Synthesis}\\addcontentsline{toc}{part}{Part II: Cross-Study Synthesis}`);
  parts.push(generateSynthesisLaTeX(papers, synthesis, topic, bibFormat));

  // Include problem statement
  parts.push(`\\newpage`);
  parts.push(`\\part*{Part III: Problem Statement}\\addcontentsline{toc}{part}{Part III: Problem Statement}`);
  parts.push(generateProblemStatementLaTeX(ps, topic, synthesis.identifiedGaps?.[ps.selectedGapIndex || 0]));

  return parts.join("\n\n");
}
